"""init_v2_pgvector

Revision ID: ab70f522bab9
Revises: b7abb6b2b89d
Create Date: 2026-03-07 23:30:04.105735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab70f522bab9'
down_revision: Union[str, Sequence[str], None] = 'b7abb6b2b89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 必须加上这一行
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 注意：通常我们不建议在 downgrade 中删除扩展，因为这可能会导致数据丢失或其他问题。
    pass
    # ### end Alembic commands ###
